### ISSUE TITLE
codegreen_core.data.energy make date column first

### ISSUE THREAD

**Issue by AnneHartebrodt** [codegreen-framework/codegreen-core#14]
```
de_2024 = cc.data.energy('DE', datetime.now()-timedelta(weeks = 52), datetime.now(), type='generation', interval60=True)
de_2024['data'].columns
```

startTimeUTC is somewhere in the middle. Will be confusing for user

**Comment by shubhvjain** [comment]
{'data':                   startTime  startTimeUTC  Biomass  Fossil Brown coal/Lignite  \
 0 2024-11-27 14:00:00+01:00  202411271300   4185.0                    11427.0   
 1 2024-11-27 14:15:00+01:00  202411271315   4231.0                    11506.0   
 2 2024-11-27 14:30:00+01:00  202411271330   4269.0                    11554.0   
 3 2024-11-27 14:45:00+01:00  202411271345   4285.0                    11597.0   
 4 2024-11-27 15:00:00+01:00  202411271400   4288.0                    11560.0   
 5 2024-11-27 15:15:00+01:00  202411271415   4195.0                    11551.0   
 6 2024-11-27 15:30:00+01:00  202411271430      NaN                        NaN   
 
    Fossil Gas  Fossil Hard coal  Fossil Oil  Geothermal  Hydro Pumped Storage  \
 0      8178.0            4027.0       317.0        21.0                1115.0   
 1      8351.0            4074.0       317.0        21.0                 435.0   
 2      8392.0            4173.0       317.0        21.0                 633.0   
 3      8425.0            4234.0       317.0        21.0                 369.0   
 4      8583.0            4271.0       317.0        21.0                 478.0   
 5      8895.0            4361.0       317.0        21.0                 960.0   
 6         NaN               NaN         NaN         NaN                   NaN   ......
