### ISSUE TITLE
Add autogenerated documentation for relevant functions in the tools section of the documentation

### ISSUE THREAD

**Issue by AnneHartebrodt** [codegreen-framework/codegreen-core#6]
Just a reminder for us to select the functions in the tools section which are to be exposed and need to be documented.

https://codegreen-framework.github.io/codegreen-core/tools.html#optimal-time-shifting

**Comment by shubhvjain** [comment]
fixed! this was due to a missing file which i mistakenly gitignored. Now docs will appear for all tools
